% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Jun-2023 11:59:08
%  MATLAB version: 9.10.0.1684407 (R2021a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('BasicSceneLiveScript.mat');

SPDtestScene = saveVarsMat.SPDtestScene; % <1x1 struct> too many elements at SPDtestScene.data.photons

ans = 3600.1;

coneExcitations = saveVarsMat.coneExcitations; % <10x375x375 double> too many elements

displayPixelSizeDegrees = [0.001515950832861867 0.001515950832861867];

displayPixelSizeMeters = [1.3229166666666665E-5 1.3229166666666665E-5];

displayedScene = saveVarsMat.displayedScene; % <1x1 struct> too many elements at displayedScene.data.photons

emPath = reshape([0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], 10, 1, 2);

i = 0.4;

nTrialsNum = 10;

presentationDisplay = saveVarsMat.presentationDisplay; % <1x1 struct> too many elements at presentationDisplay.gamma

scene = saveVarsMat.scene; % <1x1 struct> too many elements at scene.data.photons

stimParams = struct;
stimParams.spatialFrequencyCyclesPerDeg = 10;
stimParams.orientationDegs = 90;
stimParams.phaseDegs = 0;
stimParams.sizeDegs = 0.5;
stimParams.sigmaDegs = 0.099999999999999992;
stimParams.contrast = 0.9;
stimParams.meanLuminanceCdPerM2 = 40;
stimParams.pixelsAlongWidthDim = 330;
stimParams.pixelsAlongHeightDim = 330;

stimSPDtest = struct;
stimSPDtest.spatialFrequencyCyclesPerDeg = 10;
stimSPDtest.orientationDegs = 90;
stimSPDtest.phaseDegs = 0;
stimSPDtest.sizeDegs = 0.5;
stimSPDtest.sigmaDegs = 0.099999999999999992;
stimSPDtest.contrast = 0.9;
stimSPDtest.meanLuminanceCdPerM2 = 40;
stimSPDtest.pixelsAlongWidthDim = 330;
stimSPDtest.pixelsAlongHeightDim = 330;

stimtest = struct;
stimtest.spatialFrequencyCyclesPerDeg = 10;
stimtest.orientationDegs = 90;
stimtest.phaseDegs = 0;
stimtest.sizeDegs = 0.5;
stimtest.sigmaDegs = 0.033333333333333333;
stimtest.contrast = 0;
stimtest.meanLuminanceCdPerM2 = 10;
stimtest.pixelsAlongWidthDim = 330;
stimtest.pixelsAlongHeightDim = 330;

theMosaic = saveVarsMat.theMosaic; % <1x1 coneMosaicHex> unsupported class

theOI = saveVarsMat.theOI; % <1x1 struct> too many elements at theOI.data.photons

viewingDistanceMeters = 0.5;

visualizedSpatialSfrequencyCPD = 120;

visualizedSpatialSupportArcMin = 6;

clear saveVarsMat;
